services:
  mariadb:
    image: mariadb:11.4
    container_name: mariadb
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/mariadb_root_password
      MARIADB_DATABASE: schule
      MARIADB_USER: schueler
      MARIADB_PASSWORD_FILE: /run/secrets/mariadb_user_password
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    secrets:
      - mariadb_root_password
      - mariadb_user_password

volumes:
  mariadb_data:

secrets:
  mariadb_root_password:
    file: ./secrets/root_password.txt
  mariadb_user_password:
    file: ./secrets/user_password.txt

